action_noise: !!python/object:stable_baselines3.common.noise.NormalActionNoise
  _mu: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id001 !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 2
    - &id002 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      AAAAAAAAAAAAAAAAAAAAAA==
  _sigma: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 2
    - *id002
    - false
    - !!binary |
      mpmZmZmZuT+amZmZmZm5Pw==
batch_size: 128
buffer_size: 1000000
gamma: 0.99
gradient_steps: 32
learning_rate: 0.001
learning_starts: 10000
policy: MlpPolicy
policy_kwargs:
  net_arch:
  - 64
  - 64
train_freq: 64
